FROM registry.cn-shenzhen.aliyuncs.com/efucloud-public/tektoncd-golang:1.26.4 AS builder

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG GIT_COMMIT=unknown
ARG BUILD_DATE=unknown

WORKDIR /workspace

COPY . .

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -mod=vendor \
    -ldflags="-s -w \
      -X 'github.com/efucloud/kube-keeper/pkg/config.GoVersion=$(go env GOVERSION)' \
      -X 'github.com/efucloud/kube-keeper/pkg/config.Commit=${GIT_COMMIT}' \
      -X 'github.com/efucloud/kube-keeper/pkg/config.BuildDate=${BUILD_DATE}'" \
    -o /workspace/output/kube-keeper ./cmd/start.go

FROM registry.cn-shenzhen.aliyuncs.com/efucloud-public/alpine:3.23.0

ARG GIT_COMMIT=unknown
ARG BUILD_DATE=unknown

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY --from=builder /workspace/output/kube-keeper /usr/local/bin/kube-keeper
COPY config/config.yaml /efucloud/config/config.yaml

EXPOSE 9002

LABEL org.opencontainers.image.source=https://github.com/efucloud/kube-keeper
LABEL org.opencontainers.image.revision=${GIT_COMMIT}
LABEL org.opencontainers.image.created=${BUILD_DATE}

ENTRYPOINT ["/usr/local/bin/kube-keeper"]
CMD ["server", "-c", "/efucloud/config/config.yaml"]
