package models

const BuiltinShellCommandTableName = "builtin_shell_command"
const ClusterAccountTableName = "cluster_account"
const ClusterAccountPermissionTableName = "cluster_account_permission"
const ClusterNamespaceTableName = "cluster_namespace"
const ClusterAccountRoleTableName = "cluster_account_role_relation"
const ClusterApiGroupTableName = "cluster_api_group"
const ClusterApiResourceTableName = "cluster_api_resource"
const ClusterNamespaceAccountRoleTableName = "cluster_namespace_account_role_relation"
const ConfigTableName = "config"
const AccountTableName = "account"
const ClusterTableName = "cluster"
const WorkspaceTableName = "workspace"
const WorkspaceMemberTableName = "workspace_member"
const WorkspaceGitRepositoryTableName = "workspace_git_repository"
const TerminalAuditLogTableName = "terminal_audit_log"
const ApplicationTableName = "application"
const MarketApplicationTableName = "market_application"
